<?php

/**
 * @file
 * Enables the use of jQuery SmartMenus plugin for Drupal menus.
 */

/**
 * Implements hook_menu().
 */
function smartmenus_drupal_menu() {
  $items['admin/config/user-interface/smartmenus_drupal'] = array(
    'title' => 'SmartMenus',
    'description' => 'Configure SmartMenus Menus',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('smartmenus_drupal_admin_settings'),
    'access arguments' => array('administer smartmenus_drupal'),
    'file' => 'smartmenus_drupal.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function smartmenus_drupal_permission() {
  return array(
    'administer smartmenus_drupal' => array(
      'title' => t('Administer SmartMenus'),
    ),
  );
}

/**
 * Implements hook_help().
 */
function smartmenus_drupal_help($path, $arg) {
  $output = '';
  switch ($path) {
    case 'admin/modules#description':
      $output .= t('jQuery SmartMenus plugin for your Drupal menus.');
      break;

    case 'admin/config/user-interface/smartmenus_drupal':
      $output .= t('<p>Block-specific SmartMenus settings could be found at !link</p>', array('!link' => l(t('Blocks management'), 'admin/structure/block')));
      break;
  }
  return $output;
}

/**
 * Implements hook_block_info().
 */
function smartmenus_drupal_block_info() {
  $blocks = array();
  $number = variable_get('smartmenus_drupal_number', 4);
  for ($i = 1; $i <= $number; $i++) {
    $blocks[$i] = array(
      'info' => 'SmartMenus ' . $i . ' (SmartMenus)',
      'cache' => DRUPAL_NO_CACHE,
    );
  }
  return $blocks;
}


/**
 * Implements hook_block_configure().
 */
function smartmenus_drupal_block_configure($delta = 0) {
  $block_settings = variable_get('smartmenus_drupal_block_settings_' . $delta );
  $form = $menu_default = array();

  // Integration with the Domain Access module.
  if (module_exists('domain_conf')) {
    $main = variable_get('menu_main_links_source');
    $secondary = variable_get('menu_secondary_links_source');
    if ($main) {
      $menu_default['domainaccessmenu1st-' . $main . ':0'] = t('Domains Access') . ': ' . t('Main links');
    }
    if ($secondary) {
      $menu_default['domainaccessmenu2nd-' . $secondary . ':0'] = t('Domains Access') . ': ' . t('Secondary links');
    }
  }
  $menu_default += menu_parent_options(menu_get_menus(), array('mlid' => 0));

  $form['block_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Block description'),
    '#description' => t('A brief description of your block. Used on the !link', array('!link' => l(t('Blocks administration page'), 'admin/structure/block'))),
    '#default_value' => $block_settings['block_name'],
  );
  $form['sf-settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('SmartMenus settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['sf-settings']['main_menu'] = array(
    '#type' => 'select',
    '#title' => t('Menu'),
    '#description' => t('The menu you want to be displayed using SmartMenus.') . ' <em>(' . t('Default') . ': &lt;Main menu&gt;)</em>',
    '#default_value' => $block_settings['main_menu'],
    '#options' => $menu_default,
  );
  $form['sf-settings']['orientation'] = array(
    '#type' => 'radios',
    '#title' => t('Type'),
    '#default_value' => $block_settings['orientation'],
    '#options' => array(
      'horizontal' => t('Horizontal (single row)') . ' <em>(' . t('Default') . ')</em>',
      'vertical' => t('Vertical (stack)')
    ),
  );
  $form['sf-settings']['menu_style'] = array(
    '#type' => 'select',
    '#title' => t('Style'),
    '#description' => '<em>(' . t('Default') . ': ' . t('None') . ')</em>',
    '#default_value' => $block_settings['menu_style'],
    '#options' => smartmenus_drupal_styles(),
  );
  return $form;
}

/**
 * Helper function to get library paths.
 */
function smartmenus_drupal_get_path($library = 'smartmenus') {
  $directory = '';
  // Ensure the Libraries API module is installed.
  if (module_exists('libraries') && function_exists('libraries_get_path')) {
    $directory = libraries_get_path($library);
  }
  // Otherwise use the default directory.
  elseif (file_exists('profiles/' . drupal_get_profile() . '/libraries/' . $library)) {
    $directory = 'profiles/' . drupal_get_profile() . '/libraries/' . $library;
  }
  if (empty($directory)) {
    $directory = 'sites/all/libraries/' . $library;
  }
  return $directory;
}

/**
 * Implements hook_block_save().
 */
function smartmenus_drupal_block_save($delta = 0, $edit = array()) {
  // we copy the edit array directly... the $delta will be enough to diferentiate between the different blocks
  variable_set('smartmenus_drupal_block_settings_' . $delta, $edit);
}

/**
 * Get a list of CSS files that can be used for styles.
 */
function smartmenus_drupal_styles($display = 'list', $style = NULL) {
  $output = '';
  $directory = smartmenus_drupal_get_path('smartmenus') . '/css';
  //here we get our css theme files
  $css_files = array_filter(glob($directory . "/*/*.css"));
  $file_array = '';
  foreach($css_files as $css_file)
  {
    $file_array[basename($css_file, ".css" )] = $css_file;
  }

  if ($display == 'list') {
    $output = array('none' => '- ' . t('None') . ' -');
    if (is_array($file_array)) {
      foreach ($file_array as $file_name => $file_path) {
        $output[$file_name] = $file_name;
      }
    }
    natcasesort($output);
  }
  if ($display == 'path' && $style) {
    if (isset($file_array[$style])) {
      $output = array($file_array[$style] => array('type' => 'file', 'weight' => 500));
    }
    else {
      watchdog('page not found', 'Cannot find the required subdirectories for the SmartMenus \'%style\' style.', array('%style' => $style), WATCHDOG_WARNING);
      $output = '';
    }
  }
  return $output;
}

/**
 * Add require JavaScript and CSS files from the Smartmenus library.
 */
function smartmenus_drupal_library($type = NULL, $name = NULL, $action = 'add') {

  $directory = smartmenus_drupal_get_path('smartmenus');
  $sm_library = $directory . "/jquery.smartmenus.min.js\n";

  $sm_library = preg_replace("/(^[\r\n]*|[\r\n]+)[\s\t]*[\r\n]+/", "\n", trim($sm_library));

    if ($action == 'check') {
      switch ($type) {
        case  'javascript':
          switch ($name) {
            case 'drupal_behavior':
              $name = 'smartmenus_drupal.js';
              $sm_library = array(drupal_get_path('module', 'smartmenus_drupal') . '/' . $name);
              break;
            case 'core-js':
              $name = 'jquery.smartmenus.min.js';

              $sm_library = $directory . '/' . $name;
              break;
          }
          $in_library = FALSE;

              $in_library = TRUE;
              if (file_exists($sm_library)) {
                return TRUE;
              }
              else {
                watchdog('page not found', '%file', array('%file' => $directory . '/' . $name), WATCHDOG_ERROR);
                return FALSE;
              }


          if (!$in_library) {
            watchdog('page not found', '%path missing from SmartMenus library configuration, please add it immediately.', array('%path' => $directory . '/' . $name), WATCHDOG_WARNING, l(t('Superfish library configuration'), 'admin/config/user-interface/smartmenus_drupal'));
            return FALSE;
          }
          break;

        case 'CSS':
        $directory .= '/css';
          switch ($name) {
            case 'core-css':
            if (file_exists($directory . '/sm-core-css.css')) {
              return TRUE;
            }
            else {
              $css_path = $directory . '/sm-core-css.css';
              watchdog('page not found', $css_path, WATCHDOG_WARNING);
              return FALSE;
            }
              break;

            default:
            if (file_exists($directory . '/' . $name . '/' . $name . '.css')) {
              return TRUE;
            }
            else {
              $css_path = $directory . '/' . $name . '/' . $name . '.css';
              watchdog('page not found', $css_path, WATCHDOG_WARNING);
              return FALSE;
            }
              break;
          }

          break;
      } //end type switch
    } // end check action if
    if ($action == 'add') {
      switch ($type) {
        case 'javascript':
          switch ($name) {
            case 'drupal_behavior':
              $output = array(
                drupal_get_path('module', 'smartmenus_drupal') . '/smartmenus_drupal.js' =>
                array('type' => 'file', 'weight' => 495),
              );
              return $output;
            case 'core-js':
              $name = 'jquery.smartmenus.min.js';
              if (file_exists($directory . $name)) {
                  $output = array($name => array('type' => 'file', 'weight' => 470));
                  return $output;
                }
            default:
              if (file_exists($directory . '/jquery.smartmenus.min.js')) {
                    $output = array($name => array('type' => 'file', 'weight' => 470));
                    return $output;
                  }
                // If the required file did not exist in the library files list.
                if (empty($output)) {
                  watchdog('page not found', '%name cannot be found.', array('%name' => $name), WATCHDOG_WARNING);
                }
              else {
                watchdog('page not found', '%directory/jquery.smartmenus.min.js', array('%directory' => $directory), WATCHDOG_ERROR);
              }
            }
          break;

        case 'CSS':
          $directory .= '/css/';
          switch ($name) {
            case 'core-css':
              $output = array($directory . 'sm-core-css.css' => array('type' => 'file', 'weight' => 480));
              return $output;
              break;
            default:
              $output = array($directory . $name . '/' . $name . '.css' => array('type' => 'file', 'weight' => 480));
              return $output;
              break;
          }
          break;
      } //ent type switch
    } // end 'add' action if
} //end smartmenus_drupal_library function


/**
 * Implements hook_block_view().
 */
function smartmenus_drupal_block_view($delta = 0) {
  global $language;
  $block_css = $block_js = $sfoptions = $sfplugins = array();
  $block_settings = variable_get('smartmenus_drupal_block_settings_' . $delta );
  //add core css and js
  if (smartmenus_drupal_library('CSS', 'core-css', 'check')) {
    $block_css = array_merge($block_css, smartmenus_drupal_library('CSS', 'core-css', 'add'));
  }
  if (smartmenus_drupal_library('javascript', 'core-js', 'check')) {
    $block_js = array_merge($block_js, smartmenus_drupal_library('javascript', 'core-js', 'add'));
  }
  //add smartmenus-theme css
  if (smartmenus_drupal_library('CSS', $block_settings['menu_style'], 'check')) {
    $block_css = array_merge($block_css, smartmenus_drupal_library('CSS', $block_settings['menu_style'], 'add'));
    dpm($block_css);
  }

  $block['content']['#attached'] = array(
    'css' => $block_css,
    'js' => $block_js,
  );
return $block;
} // end smartmenus_drupal_block_view function
